In [1]:
import pandas as pd
import numpy as np

In [13]:
iris=np.loadtxt('./iris.txt', dtype=object, delimiter=' ', skiprows=1)
iris[:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype=object)

求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

In [17]:
sepallength=np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1, usecols=[0])
x=np.mean(sepallength)
y=np.median(sepallength)
z=np.std(sepallength)
x,y,z

(5.843333333333334, 5.8, 0.8253012917851409)

创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）

In [19]:
mi=np.amin(sepallength)
mx=np.amax(sepallength)
x=(sepallength-mi)/(mx-mi)
x

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

In [20]:
x=np.percentile(sepallength,[5,95])
x

array([4.6  , 7.255])

把iris_data数据集中的20个随机位置修改为np.nan值。

In [33]:
x,y=iris.shape
iris[np.random.randint(x,size=20),np.random.randint(1,y,size=20)]=np.nan
iris

array([['5.1', '3.5', nan, '0.2', 'Iris-setosa'],
       ['4.9', '3', '1.4', nan, 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', nan, nan, '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', nan, 'Iris-setosa'],
       ['5', nan, '1.5', '0.2', nan],
       ['4.4', '2.9', nan, nan, 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', nan],
       ['4.8', nan, '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3', nan, '0.1', 'Iris-setosa'],
       ['4.3', '3', nan, '0.1', nan],
       ['5.8', '4', '1.2', '0.2', nan],
       ['5.7', '4.4', '1.5', '0.4', nan],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', nan],
       ['5.7', nan, '1.7', '0.3', nan],
       ['5.1', '3.8', '1.5', nan, nan],
       ['5.4', '3.4', nan, '0.2', nan],
       ['5.1', '3.7', '1.5', '0.4', na

在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

In [36]:
iris = np.loadtxt('./iris.txt', dtype=float, delimiter=' ',skiprows=1, usecols=[0,1,2,3])
i, j = iris.shape
np.random.seed(20201201)
iris[np.random.choice(i, size= 20), np.random.choice(j, size= 20)] = np.nan
sepallength = iris[:,0]
x=sum(np.isnan(sepallength))
y=np.where(np.isnan(sepallength))
x,y

(3, (array([ 95, 101, 144], dtype=int64),))

筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

In [42]:
iris = np.loadtxt('./iris.txt', dtype=float, delimiter=' ',skiprows=1,usecols=[0,2])
a = np.where(np.logical_and(iris[:,1] > 1.5,iris[:,0] < 5.0))
iris[a]

array([[4.8, 1.6],
       [4.8, 1.9],
       [4.7, 1.6],
       [4.8, 1.6],
       [4.9, 3.3],
       [4.9, 4.5]])

选择没有任何 nan 值的 iris_data行。

In [45]:
np.random.seed(20201201)
iris= np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1,usecols=[0,1,2,3])
a,b= iris.shape
iris[np.random.randint(a, size=20), np.random.randint(b, size=20)] = np.nan
x = iris[np.sum(np.isnan(iris), axis=1) == 0]
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3

计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

In [46]:
iris= np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1,usecols=[0,2])
x = np.corrcoef(iris[:,0], iris[:,1])
x

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

In [48]:
iris= np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1,usecols=[0,1,2,3])
x = np.isnan(iris)
np.any(x)

False

在numpy数组中将所有出现的nan替换为0。

In [49]:
np.random.seed(20201201)
iris= np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1,usecols=[0,1,2,3])
a,b= iris.shape
iris[np.random.randint(a, size=20), np.random.randint(b, size=20)] = np.nan
iris[np.isnan(iris)]=0
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 0. , 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 0. , 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0. ],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 0. , 0. , 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

In [51]:
iris = np.loadtxt('./iris.txt', dtype=object, delimiter=' ',skiprows=1, usecols=[4])
x = np.unique(iris, return_counts=True) 
x

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([50, 50, 50], dtype=int64))

将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 -->‘small’；3-5 --> ‘medium’；’>=5 --> ‘large’。

In [52]:
iris= np.loadtxt('./iris.txt', dtype=float, delimiter=' ', skiprows=1,usecols=[2])
a=np.amin(iris)
b=np.amax(iris) # 1.0  6.9
inds = np.digitize(iris, [0,3,5,7])
lable = {1: 'small',2: 'medium',3: 'large'}
p = [lable[x] for x in inds]
print(p)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3 。

In [55]:
iris= np.loadtxt('./iris.txt', dtype=object, delimiter=' ', skiprows=1)
sepallength = iris[:, 0].astype(float)
petallength = iris[:, 2].astype(float)
volume=(np.pi* petallength*sepallength ** 2)/ 3
volume = volume[:, np.newaxis]
iris= np.concatenate([iris, volume], axis=1)
iris[:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa', 38.13265162927291],
       ['4.9', '3', '1.4', '0.2', 'Iris-setosa', 35.200498485922445],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa', 30.0723720777127],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa', 33.238050274980004],
       ['5', '3.6', '1.4', '0.2', 'Iris-setosa', 36.65191429188092]],
      dtype=object)

随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。

In [57]:
np.random.seed(20201201)
species = np.array(['setosa', 'versicolor', 'virginica'])
species_out = np.random.choice(species, 10000, p=[0.5, 0.25, 0.25])
np.unique(species_out, return_counts=True)

(array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 array([5031, 2479, 2490], dtype=int64))

根据 sepallength 列对数据集进行排序。

In [59]:
iris= np.loadtxt('./iris.txt', dtype=object, delimiter=' ', skiprows=1)
sepallength = iris[:, 0].astype(float)
index = np.argsort(sepallength)
iris[index]

array([['4.3', '3', '1.1', '0.1', 'Iris-setosa'],
       ['4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.4', '3', '1.3', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
       ['4.6', '3.6', '1', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3', '1.4', '0.1', 'Iris-setosa'],
       ['4.8', '3', '1.4', '0.3', 'Iris-setosa'],
       ['4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
       ['4.9', '2.4', '3.3', '1', 'Iris-versicolor'],
       ['4.9', '2.5', '4.5', '1.7', 'Iris-virginica'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['4.9', '3

在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）。

In [62]:
iris= np.loadtxt('./iris.txt', dtype=object, delimiter=' ', skiprows=1)
a, b = np.unique(iris[:, 2].astype(float), return_counts=True)
a,b
print(a[np.argmax(b)]) 
print(np.amax(b))

1.5
14


在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置。

In [73]:
iris= np.loadtxt('./iris.txt', dtype=object, delimiter=' ', skiprows=1)
petalwidth=iris[:, 2].astype(float)
a=np.where(petalwidth > 1.0)
a[0][0],iris[a[0][0]]

(0, array(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype=object))