In [1]:
import numpy as np
outfile = r'.\test.npy'
np.random.seed(20200619) #seed( ) 用于指定随机数生成时所用算法开始的整数值
x = np.random.uniform(0, 1, [3, 5]) #函数原型：  numpy.random.uniform(low,high,size) 
#功能：从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开，即包含low，不包含high. 
#参数介绍:     
#low: 采样下界，float类型，默认值为0； 
#high: 采样上界，float类型，默认值为1； 
#size: 输出样本数目，为int或元组(tuple)类型，例如，size=(m,n,k), 则输出m*n*k个样本，缺省时输出1个值。 
#返回值：ndarray类型，其形状和参数size中描述一致。 
#a. randint: 原型：numpy.random.randint(low, high=None, size=None, dtype='l')，产生随机整数； 
#b. random_integers: 原型： numpy.random.random_integers(low, high=None, size=None)，在闭区间上产生随机整数； 
#c. random_sample: 原型： numpy.random.random_sample(size=None)，在[0.0,1.0)上随机采样； 
#d. random: 原型： numpy.random.random(size=None)，和random_sample一样，是random_sample的别名； 
#e. rand: 原型： numpy.random.rand(d0, d1, ..., dn)，产生d0 - d1 - ... - dn形状的在[0,1)上均匀分布的float型数。 
#f. randn: 原型：numpy.random.randn（d0,d1,...,dn),产生d0 - d1 - ... - dn形状的标准正态分布的float型数。 
np.save(outfile, x)
y = np.load(outfile)
print(y)

[[0.01123594 0.66790705 0.50212171 0.7230908  0.61668256]
 [0.00668332 0.1234096  0.96092409 0.67925305 0.38596837]
 [0.72342998 0.26258324 0.24318845 0.98795012 0.77370715]]


In [3]:
import numpy as np

outfile = r'.\test.npz'
x = np.linspace(0, np.pi, 5) #在指定的间隔范围内返回均匀间隔的数字。
y = np.sin(x)
z = np.cos(x)
np.savez(outfile, x, y, z_d=z)
data = np.load(outfile)
np.set_printoptions(suppress=True)
print(data.files)  

[[0.01123594 0.66790705 0.50212171 0.7230908  0.61668256]
 [0.00668332 0.1234096  0.96092409 0.67925305 0.38596837]
 [0.72342998 0.26258324 0.24318845 0.98795012 0.77370715]]


In [5]:
import numpy as np

outfile = r'.\test.npz'
x = np.linspace(0, np.pi, 5)

In [7]:
y = np.sin(x)

In [9]:
z = np.cos(x)

In [12]:
np.savez(outfile, x, y, z_d=z)

In [13]:
data = np.load(outfile)

In [15]:
np.set_printoptions(suppress=True)
print(data.files)  

['z_d', 'arr_0', 'arr_1']


In [18]:
data['z_d'],data['arr_0'],data['arr_1']

(array([ 1.        ,  0.70710678,  0.        , -0.70710678, -1.        ]),
 array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265]),
 array([0.        , 0.70710678, 1.        , 0.70710678, 0.        ]))

In [30]:
files=r'.\test.txt'
x=np.arange(0,10).reshape(5,2)
np.savetxt(files,x)
data=np.loadtxt(files)
print(data)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [26]:
outfile = r'.\test.csv'
x = np.arange(0, 10, 0.5).reshape(4, -1)
np.savetxt(outfile, x, fmt='%.3f', delimiter=',')
y = np.loadtxt(outfile, delimiter=',')
print(y)

[[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7. ]
 [7.5 8.  8.5 9.  9.5]]


In [39]:
x = np.linspace(0, np.pi, 8)

In [40]:
np.set_printoptions(precision=3,threshold=6) #保留三位小数

In [42]:
np.set_printoptions(threshold=np.iinfo(np.int).max)#连续不中断

In [43]:
x

array([0.   , 0.449, 0.898, 1.346, 1.795, 2.244, 2.693, 3.142])