计算两个矩阵的乘积，如果是一维数组则是它们的内积。

In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([2,3,4,5,6])
z=np.dot(x,y)
z

70

#矩阵特征值与特征向量
#numpy.linalg.eig(a) 计算方阵的特征值和特征向量。
#numpy.linalg.eigvals(a) 计算方阵的特征值。

求方阵的特征值特征向量

In [2]:
import numpy as np

In [3]:
x=np.diag((1,2,3))
y=np.linalg.eigvals(x)
z,s=np.linalg.eig(x)

In [4]:
x,y,z,s

(array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [6]:
for i in range(3): 
    if np.allclose(z[i] * s[:, i], np.dot(x, s[:, i])):
        print(True)

True
True
True


In [7]:
#判断对称阵是否为正定阵
A = np.arange(16).reshape(4, 4)
print(A)
A = A + A.T  # 将方阵转换成对称阵
print(A)
B = np.linalg.eigvals(A)  # 求A的特征值
print(B)
# 判断是不是所有的特征值都大于0，用到了all函数，显然对称阵A不是正定的
if np.all(B > 0):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01 -7.41657387e+00  1.82694656e-15 -1.72637110e-15]
No


练习题
1、计算两个数组a和b之间的欧氏距离

In [8]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
d=np.linalg.norm(a - b)
d

6.708203932499369

In [11]:
z=np.sqrt(np.sum((a-b)**2))
z

6.708203932499369

In [13]:
# 2、计算矩阵的行列式和矩阵的逆
x=np.diag([5,5,5,5,5])
z=np.linalg.det(x)
y=np.linalg.inv(x)
z,y

(3124.999999999999, array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.2,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0.2,  0. ,  0. ],
        [-0. , -0. , -0. ,  0.2, -0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0.2]]))

In [14]:
#3、给定矩阵A和数组b，求解线性方程式
A=np.array([[1, -2, 1],[0 ,2 ,-8],[-4, 5 ,9]])
b=np.array([0,8,-9])
x=np.linalg.solve(A,b)
x

array([29., 16.,  3.])

In [15]:
#4、给定矩阵A[[4,-1,1],[-1,3,-2],[1,-2,3]]计算特征值和特征向量
A=np.array([[4,-1,1],[-1,3,-2],[1,-2,3]])
z,s=np.linalg.eig(A)
z,s

(array([3., 6., 1.]),
 array([[-8.16496581e-01, -5.77350269e-01,  3.89855447e-17],
        [-4.08248290e-01,  5.77350269e-01,  7.07106781e-01],
        [ 4.08248290e-01, -5.77350269e-01,  7.07106781e-01]]))